# -*- coding: utf-8 -*-
"""Conway's Game Life.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11c7kzLKYkFG2Go3jMnDlymdh3Lhyu_yE
"""

#Colab do not support animation, for animation please run this code on pycharm
#You must install matplotlib on pycharm otherwise, this will give an error
import copy
import matplotlib.pyplot as plt
R = int(5)
C = int(5)
generations = int(3)
matrix = []
matrix1 = []

data = []

def initial_state():
    for i in range(R):
        A = []
        B = []
        for j in range(C):
            if (i == 1 and (j == 2 or j == 3 or j == 4)) or (i == 2 and (j == 1 or j == 2 or j == 3)):
                A.append(int(1))
            else:
                A.append(int(0))
            B.append(int(0))
        matrix.append(A)
        matrix1.append(B)


def conways():
    count = 0
    #print(matrix)
    for i in range(R):
        for j in range(C):
            if matrix[i][j] == 0:
                if (i-1) <= -1 and (j-1) <= -1:
                    if matrix[0][1] == 1:
                        count = count+1
                    if matrix[1][0] == 1:
                        count = count+1
                    if matrix[1][1] == 1:
                        count = count+1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                elif i+1 >= R and j+1 >= C:
                    if matrix[i][j-1] == 1:
                        count = count + 1
                    if matrix[i-1][C-1] == 1:
                        count = count + 1
                    if matrix[i-1][C-2] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                    #print(f"here{matrix1}")
                elif j-1 <= -1 and i+1 == R:
                    if matrix[i][j+1] == 1:
                        count = count + 1
                    if matrix[i-1][0] == 1:
                        count = count + 1
                    if matrix[i-1][1] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                elif j + 1 == C and i == 0:
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i + 1][R-1] == 1:
                        count = count + 1
                    if matrix[i - 1][R-2] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                elif i-1 <= -1:
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i][j-1] == 1:
                        count = count + 1
                    if matrix[i+1][j] == 1:
                        count = count + 1
                    if matrix[i+1][j+1] == 1:
                        count = count + 1
                    if matrix[i+1][j-1] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                elif i+1 >= R:
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i][j-1] == 1:
                        count = count + 1
                    if matrix[i-1][j] == 1:
                        count = count + 1
                    if matrix[i-1][j+1] == 1:
                        count = count + 1
                    if matrix[i-1][j-1] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                elif j-1 <= -1:
                    #print(i,j)
                    if matrix[i][j+1] == 1:
                        count = count + 1
                    if matrix[i-1][0] == 1:
                        count = count + 1
                    if matrix[i-1][1] == 1:
                        count = count + 1
                    if matrix[i+1][0] == 1:
                        count = count + 1
                    if matrix[i+1][1] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    #print(f"Count{count}")
                    #print(f"yes:{matrix1[i][j]}")
                    count = 0
                elif j+1 == C:
                    if matrix[i][j-1] == 1:
                        count = count + 1
                    if matrix[i-1][C-1] == 1:
                        count = count + 1
                    if matrix[i-1][C-2] == 1:
                        count = count + 1
                    if matrix[i+1][C-1] == 1:
                        count = count + 1
                    if matrix[i+1][C-2] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
                else:
                    if matrix[i][j-1] == 1:
                        count = count + 1
                    if matrix[i][j+1] == 1:
                        count = count + 1
                    if matrix[i-1][j] == 1:
                        count = count + 1
                    if matrix[i-1][j-1] == 1:
                        count = count + 1
                    if matrix[i-1][j+1] == 1:
                        count = count + 1
                    if matrix[i + 1][j] == 1:
                        count = count + 1
                    if matrix[i + 1][j-1] == 1:
                        count = count + 1
                    if matrix[i + 1][j+1] == 1:
                        count = count + 1
                    if count == 3:
                        matrix1[i][j] = 1
                    count = 0
            else:
                if (i - 1) <= -1 and (j - 1) <= -1:
                    #print(f"1{i, j}")
                    if matrix[0][1] == 1:
                        count = count + 1
                    if matrix[1][0] == 1:
                        count = count + 1
                    if matrix[1][1] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                elif i + 1 >= R and j + 1 >= C:
                    #print(f"2{i, j}")
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][C - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][C - 2] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                    #print(f"87874here{matrix1}")
                elif j - 1 <= -1 and i + 1 == R:
                    #print(f"3{i, j}")
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i - 1][0] == 1:
                        count = count + 1
                    if matrix[i - 1][1] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                elif j + 1 == C and i == 0:
                    #print(f"4{i, j}")
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i + 1][R - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][R - 2] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                elif i - 1 <= -1:
                    #print(f"5{i, j}")
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i + 1][j] == 1:
                        count = count + 1
                    if matrix[i + 1][j + 1] == 1:
                        count = count + 1
                    if matrix[i + 1][j - 1] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                elif i + 1 >= R:
                    #print(f"6{i, j}")
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][j] == 1:
                        count = count + 1
                    if matrix[i - 1][j + 1] == 1:
                        count = count + 1
                    if matrix[i - 1][j - 1] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                elif j - 1 <= -1:
                    #print(f"7{i, j}")
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i - 1][0] == 1:
                        count = count + 1
                    if matrix[i - 1][1] == 1:
                        count = count + 1
                    if matrix[i + 1][0] == 1:
                        count = count + 1
                    if matrix[i + 1][1] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                elif j + 1 == C:
                    #print(f"8{i, j}")
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][C - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][C - 2] == 1:
                        count = count + 1
                    if matrix[i + 1][C - 1] == 1:
                        count = count + 1
                    if matrix[i + 1][C - 2] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0
                else:
                    #print(f"9{i, j}")
                    if matrix[i][j - 1] == 1:
                        count = count + 1
                    if matrix[i][j + 1] == 1:
                        count = count + 1
                    if matrix[i - 1][j] == 1:
                        count = count + 1
                    if matrix[i - 1][j - 1] == 1:
                        count = count + 1
                    if matrix[i - 1][j + 1] == 1:
                        count = count + 1
                    if matrix[i + 1][j] == 1:
                        count = count + 1
                    if matrix[i + 1][j - 1] == 1:
                        count = count + 1
                    if matrix[i + 1][j + 1] == 1:
                        count = count + 1
                    if count > 3:
                        matrix1[i][j] = 0
                    elif count == 2 or count == 3:
                        matrix1[i][j] = 1
                    elif count < 2:
                        matrix1[i][j] = 0
                    #print(count)
                    count = 0


initial_state()
for i in range(R):
    for j in range(C):
        print(matrix[i][j], end=" ")
    print()

data.append(matrix)
for i in range(generations-1):
    conways()
    matrix = copy.deepcopy(matrix1)
    #matrix = matrix1
    x = copy.deepcopy(matrix1)
    print("==================================")
    data.append(x)
    for i in range(R):
        for j in range(C):
            print(x[i][j], end=" ")
        print()



print("==================================")
for i in range(len(data)):
    plt.cla()
    plt.title('matplotlib.pyplot.pause() function\n\n Window {}'.format(i+1), fontweight="bold")
    plt.imshow(data[i])
    plt.pause(1)